## Autoload singleton. The game loop: drop the player at a random cell in
## the city-maze, they navigate (by sight alone, no compass/waypoint UI) to
## a glowing beacon placed at a graph-distant cell -- not just a random
## point, but one picked via BFS over the maze graph to guarantee a genuinely
## long, winding solution path each round. Reaching it starts a new round.
##
## City geometry + maze graph come from environment/city.glb and
## environment/city_maze.json, both generated by tools/generate_city.py
## (run via `blender --background --python tools/generate_city.py` -- see
## that script to tweak layout/regenerate).
extends Node3D

@export var win_distance := 2.0   ## meters; how close counts as "arrived"
@export var respawn_delay := 2.0  ## seconds to pause before the next round

var _origin: XROrigin3D
var _target_position: Vector3
var _round_active := false
var _beacon: MeshInstance3D

var _grid_size: int
var _cells: Array = []       # Vector3 world position per cell, index = row * grid_size + col
var _open_e: Array = []      # [row][col] bool -- passage to col+1
var _open_n: Array = []      # [row][col] bool -- passage to row+1


func _ready() -> void:
	call_deferred("_start")


func _start() -> void:
	var camera := get_viewport().get_camera_3d()
	if camera == null:
		call_deferred("_start")
		return
	_origin = camera.get_parent() as XROrigin3D
	if _origin == null:
		push_error("VisionQuestGame|FATAL: XR camera's parent isn't an XROrigin3D")
		return

	_build_city()
	if not _load_maze_graph():
		push_error("VisionQuestGame|FATAL: could not load city_maze.json")
		return

	_new_round()


func _process(_delta: float) -> void:
	if not _round_active or _origin == null:
		return
	var flat_origin := _origin.global_position
	var flat_target := _target_position
	flat_origin.y = 0.0
	flat_target.y = 0.0
	if flat_origin.distance_to(flat_target) <= win_distance:
		_on_target_reached()


func _on_target_reached() -> void:
	_round_active = false
	print("VisionQuestGame|INFO: target reached!")
	await get_tree().create_timer(respawn_delay).timeout
	_new_round()


# ---------------------------------------------------------------------------
# City geometry
# ---------------------------------------------------------------------------
func _build_city() -> void:
	var city_scene := load("res://environment/city.glb") as PackedScene
	var city := city_scene.instantiate()
	add_child(city)
	_generate_collision(city)


## glTF imports have no collision by default; walk the tree once and give
## every mesh trimesh collision so the maze walls/buildings are solid.
func _generate_collision(node: Node) -> void:
	var mesh_inst := node as MeshInstance3D
	if mesh_inst:
		mesh_inst.create_trimesh_collision()
	for child in node.get_children():
		_generate_collision(child)


# ---------------------------------------------------------------------------
# Maze graph (for picking genuinely hard spawn/target pairs)
# ---------------------------------------------------------------------------
func _load_maze_graph() -> bool:
	var f := FileAccess.open("res://environment/city_maze.json", FileAccess.READ)
	if f == null:
		return false
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if parsed == null:
		return false

	_grid_size = parsed["grid_size"]
	_cells.clear()
	for c in parsed["cells"]:
		# Blender export used (x, y) on its ground plane; Blender's glTF
		# export maps Blender Y to Godot -Z (Blender is Z-up, glTF/Godot are
		# Y-up), so the sign flip here keeps these positions matching where
		# the actual geometry landed after import.
		_cells.append(Vector3(c[0], 0.0, -c[1]))
	_open_e = parsed["open_e"]
	_open_n = parsed["open_n"]
	return true


func _neighbors(cell: Vector2i) -> Array:
	var row := cell.x
	var col := cell.y
	var result: Array = []
	if col + 1 < _grid_size and bool(_open_e[row][col]):
		result.append(Vector2i(row, col + 1))
	if col - 1 >= 0 and bool(_open_e[row][col - 1]):
		result.append(Vector2i(row, col - 1))
	if row + 1 < _grid_size and bool(_open_n[row][col]):
		result.append(Vector2i(row + 1, col))
	if row - 1 >= 0 and bool(_open_n[row - 1][col]):
		result.append(Vector2i(row - 1, col))
	return result


func _bfs_distances(start: Vector2i) -> Dictionary:
	var dist := {start: 0}
	var queue: Array = [start]
	var head := 0
	while head < queue.size():
		var cur: Vector2i = queue[head]
		head += 1
		for n in _neighbors(cur):
			if not dist.has(n):
				dist[n] = dist[cur] + 1
				queue.append(n)
	return dist


func _cell_position(cell: Vector2i) -> Vector3:
	return _cells[cell.x * _grid_size + cell.y]


func _new_round() -> void:
	var spawn_cell := Vector2i(randi() % _grid_size, randi() % _grid_size)
	var dist := _bfs_distances(spawn_cell)

	var max_dist := 0
	for d in dist.values():
		max_dist = max(max_dist, d)

	var far_cells: Array = []
	for cell in dist.keys():
		if cell != spawn_cell and dist[cell] >= max_dist - 1:
			far_cells.append(cell)
	if far_cells.is_empty():
		far_cells = [spawn_cell]

	var target_cell: Vector2i = far_cells[randi() % far_cells.size()]

	var spawn := _cell_position(spawn_cell)
	var target := _cell_position(target_cell)
	_origin.global_position = spawn
	_target_position = target
	_place_beacon(target)
	_round_active = true
	print("VisionQuestGame|INFO: new round. spawn_cell=%s target_cell=%s maze_distance=%d" %
		[spawn_cell, target_cell, dist[target_cell]])


func _place_beacon(pos: Vector3) -> void:
	if _beacon == null:
		var mesh := SphereMesh.new()
		mesh.radius = 0.4
		mesh.height = 0.8
		var mat := StandardMaterial3D.new()
		mat.emission_enabled = true
		mat.emission = Color(1.0, 0.85, 0.2)
		mat.emission_energy_multiplier = 4.0
		_beacon = MeshInstance3D.new()
		_beacon.mesh = mesh
		_beacon.material_override = mat
		add_child(_beacon)
	_beacon.global_position = pos + Vector3(0, 1.0, 0)
